version: "3.3"
services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - '443:443'
    depends_on:
      - wordpress
    networks:
      - my_network
    volumes:
      - wpdata:/var/www/html
    restart: always
  mariadb:
    build:
      context: ./requirements/mariadb
      args:
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        DB_USER: $DB_USER
        DB_PASSWORD: $DB_PASSWORD
        DB_NAME: $DB_NAME
    container_name: mariadb
    volumes:
      - mariadbdata:/var/lib/mysql
    networks:
      - my_network
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    environment:
    - MYSQL_HOST=$MYSQL_HOST
    - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    - WP_DB_USER=$DB_USER
    - WP_DB_PASSWORD=$DB_PASSWORD
    - WP_DB_NAME=$DB_NAME
    - WP_URL=$WP_URL
    - WP_TITLE=$WP_TITLE
    - WP_ADMIN_EMAIL=$WP_ADMIN_EMAIL
    - WP_ADMIN_LOGIN=$WP_ADMIN_LOGIN
    - WP_ADMIN_PASSWORD=$WP_ADMIN_PASSWORD
    - WP_USER_LOGIN=$WP_USER_LOGIN
    - WP_USER_EMAIL=$WP_USER_EMAIL
    - WP_USER_PASSWORD=$WP_USER_PASSWORD
    ports:
      - '9000:9000'
    depends_on:
      - mariadb
    networks:
      - my_network
    volumes:
      - wpdata:/var/www/html/
    restart: always
  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    networks:
      - my_network
    ports:
      - '21:21'
      - '20:20'
    environment:
    - FTP_USER=$FTP_USER
    - FTP_PASS=$FTP_PASS
    volumes:
      - wpdata:/var/www/html/
    restart: always
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    ports:
      - '6379:6379'
    networks:
     - my_network
    depends_on:
      - mariadb
    restart: always
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    ports:
      - '30000:8080'
    depends_on:
      - mariadb
    networks:
      - my_network
    volumes:
      - wpdata:/var/www/html/
    restart: always 
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    ports:
     - '8080:8080'
    networks:
     - my_network
    restart: unless-stopped
    privileged: true
    user: root
    volumes:
      - jenkinsstorage:/var/jenkins_home/
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
networks:
  my_network:
    driver: bridge
volumes:
  jenkinsstorage:
  mariadbdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/data/mariadb
  wpdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/data/html
