CREATE USER 'root'@'%' IDENTIFIED BY 'root123';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'hbourkan'@'%' IDENTIFIED BY 'inception123';
GRANT ALL PRIVILEGES ON wordpress.* TO 'hbourkan'@'%' IDENTIFIED BY 'inception123';
FLUSH PRIVILEGES;
